// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7O1VpeJDiG2V_TLouuLxDRFKG55bZF9A',
    appId: '1:415783699156:web:0d3e07f75b27d4c5b13141',
    messagingSenderId: '415783699156',
    projectId: 'dartt-step',
    authDomain: 'dartt-step.firebaseapp.com',
    storageBucket: 'dartt-step.appspot.com',
    measurementId: 'G-XNEN04PFFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSAAEupyq8G_33v28piJYah_JN7vCjZFI',
    appId: '1:415783699156:android:180b64525d901d98b13141',
    messagingSenderId: '415783699156',
    projectId: 'dartt-step',
    storageBucket: 'dartt-step.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvC2qcjaDNm8-Ryyk4CqY1LxAVuf8SBGM',
    appId: '1:415783699156:ios:6e5443489c8094c7b13141',
    messagingSenderId: '415783699156',
    projectId: 'dartt-step',
    storageBucket: 'dartt-step.appspot.com',
    iosBundleId: 'com.example.darttTot',
  );
}
